### ISSUE TITLE
defaultValue for type Array null

### ISSUE THREAD

**Issue by Townsheriff** [75lb/command-line-args#24]
Fails to parse command line if defaultValue is null and type is String and multiple is true.

Using following options: 

```
    {
        name: 'tags',
        alias: 't',
        type: String,
        multiple: true,
        defaultValue: null
    },
```

If `--tags` array values are provided in CLI then it parses them incorrectly. Last string is split in array of chars and everything else is ignored.

**Comment by 75lb** [comment]
hi.. this is a rare use case - by specifying `multiple: true` you are telling command-line-args to return an array of zero or more values.. you don't need to specify `defaultValue` on a multiple, because you will always get an array back. 

Still, i will look at this and potentially add some validation to prevent incorrect usage.. 

So, you want `options.tags` to return `null` (if no `--tags` were supplied) or `[ 'tag1', 'tag2' etc ]` if `--tags tag1 tag2 etc` was supplied, correct?

**Comment by Townsheriff** [comment]
Hi, no, it was a bug in my code and unexpected behaviour from package. Being a good person I reported it.
If no tags was supplies `--tags` then `options.tags` was null, but if `--tags tag1 tag2` then `options.tags` was `['t', 'a', 'g', '2']`

**Comment by 75lb** [comment]
was unable to reproduce your particular `['t', 'a', 'g', '2']` output but did find a fix a bug.. 

the intended behaviour is that if `multiple: true` is set, you are guaranteed an array back in the output.. So, if your option definition is 

```
{
  name: 'tags',
  alias: 't',
  type: String,
  multiple: true,
  defaultValue: null
},
```

and you did not pass a value for `--tags` on the command line, then your output would be 

```
{
  tags: [ null ]
}
```

i.e. your default value as an array, as `multiple: true` guarantees an array. 

You would get the same output if your definition looked like this: 

```
{
  name: 'tags',
  alias: 't',
  type: String,
  multiple: true,
  defaultValue: [ null ]
},
```
